version: "3.7"

networks:
  php74.network:
    driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    container_name: php74.php
    depends_on:
      - mysql
    # - postgres
    # - redis
    # - mariadb
    networks:
      - php74.network
    ports:
      - "${PHP_PORTS}:9000"
    volumes:
      - .:/var/www/app.dev

  nginx:
    build: ./docker/nginx
    container_name: php74.nginx
    restart: always
    tty: true
    depends_on:
      - php
      - mysql
      # - postgres
      # - redis
      # - mariadb
    ports:
      - "${WEB_PORTS}:80"
      - "${SSL_PORTS}:433"
    volumes:
      - .:/var/www/app.dev
    networks:
      - php74.network

  # apache:
  #   build: ./docker/apache
  #   restart: always
  #   container_name: php74.apache
  #   networks:
  #     - php74.network
  #   depends_on:
  #     - php
  #     # - mysql
  #     # - postgres
  #     # - redis
  #     # - mariadb
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - .:/var/www/app.dev

  #  mariadb:
  #    image: mariadb
  #    tty: true
  #    restart: always
  #    container_name: php74.mariadb
  #    networks:
  #      - php74.network
  #    ports:
  #      - '3306:3306'
  #    volumes:
  #      - './docker/mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
  #      - './docker/mysql/dbdata:/var/lib/mysql'
  #    environment:
  #      - MYSQL_PASSWORD=root
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=development

  mysql:
    build: ./docker/mysql
    tty: true
    restart: always
    container_name: php74.mysql
    networks:
      - php74.network
    ports:
      - "${MYSQL_PORTS}:3306"
    volumes:
      - "./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./docker/mysql/dbdata:/var/lib/mysql"
      - ./docker/mysql/sqlfile:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  phpmyadmin:
    image: library/phpmyadmin
    container_name: php74.phpmyadmin
    tty: true
    networks:
      - php74.network
    depends_on:
      - mysql
    environment:
      PMA_HOSTS: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}    
    ports:
      - '${PHPMYADMIN_WEBPORTS}:80'

  # postgres:
  #   build: ./docker/postgres
  #   container_name: php74.postgres
  #   tty: true
  #   restart: always
  #   networks:
  #     - php74.network
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - "./docker/postgres/dbdata:/var/lib/postgresql/data"
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=development

  # redis:
  #   image: bitnami/redis:latest
  #   restart: always
  #   tty: true
  #   container_name: php74.redis
  #   volumes:
  #     - ./docker/redis:/bitnami/redis/data
  #   networks:
  #     - php74.network
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - REDIS_PASSWORD=root
  #   ports:
  #     - "6379:6379"
